### ISSUE TITLE
Not able to use Alvium 1500c-210c CSI-2 camera working with Jetson Nano

### ISSUE THREAD

**Issue by krs1980** [alliedvision/examples#5]
I am working on a project that uses Alvium 1500c-210c CSI-2 camera. I have prepared Jetpack using SDK as instructed in https://github.com/alliedvision/linux_nvidia_jetson/issues/13 by BernardoLuck. I have also installed necessary drivers. I am able to detect the camera node using ls /dev and v4l2-ctl --list-devices. I downloaded and installed Vimba for the further development. But I am stuck as the camera doesn't show up in VimbaViewer. I have compiled VimbaViewer from the directory. So I have few questions:
1. Is CSI-2 camera supported by Vimba and VimbaPython?
2. If answer to above question is "Yes", is there an example in Vimba or VimbaPython to get the camera output?
3. If the answer to my first question is "No", is there any other method to use the camera

At the moment I am stuck. Plz help.

**Comment by BernardoLuck** [comment]
Hi, 

as it is mentioned in the Vimba manual, Vimba cannot control CSI-2 cameras yet, because there is still not GenICam support for CSI-2. A this moment, CSI-2 camera can only be controlled via V4L2 or with DRA(direct register access). 

The best way is to create your code based on V4L2, like in our code-examples. A support for CSI-2 camera using Vimba will be available very soon. If you prefer to work with Vimba, then I suggest to wait a few weeks. We will make an announcement on our Website regarding this implementation. If you need to deploy your code as soon as possible then I recommend to work with V4L2.

BR

Bernardo Luck Villanueva // Applications Engineer

Allied Vision Technologies GmbH
Klaus-Groth-Str. 1, 22926 Ahrensburg, Germany
T // +49 (4102) 6688-270 F // +49 (4102) 6688-269
Managing Directors: Alexander van der Lof, Hanno Schulz | Registration Office: AG Jena HRB 208962 | Headquarters: Taschenweg 2a, 07646 Stadtroda, Germany

**Comment by krs1980** [comment]
Dear Bernardo Luck Villanueva,

Thank you very much for your quick response. I have build BasicV4L2 example, but it throws error “No device selected”. If I run GStreamer example, I just get a black and white stream. Would you suggest some way to view the camera feed, manage camera settings and read images for the real application. At the moment it appears a dark road ahead.

Your support would be highly appreciated.

Kind  Regards
Ram Seervi (Team Leader - Embedded)

[A picture containing drawing  Description automatically generated]
Email: ***@***.******@***.***> I web: www.monarch-innovation.com<http://www.monarch-innovation.com/>.
M:+91-93272 56002
________________________________
This e-mail, including any attached files, may contain confidential and privileged information for the sole use of the intended recipient.  Any review, use, distribution, or disclosure by others is strictly prohibited.  If you are not the intended recipient (or authorized to receive information for the intended recipient), please contact the sender by reply e-mail and delete all copies of this message

**Comment by krs1980** [comment]
The error thrown when running example BasicV4L2 ("No device found") was due to the fact that the command expected arguments. I was not aware that the example expected few arguments to be passed through command line. As I was not specifying camera node, it was not working. I did following and I could see camera feed in window:
./BasicDemo -d /dev/video0
Feed other values as per options.

It would have been better to include an example command in readme.txt, it would help novice users.
